name: CI

env:
  node-version: 16.x

on:
  push: 
    branches:
      - main
      - develop
  pull_request: {}
  workflow_dispatch: {}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: ${{env.node-version}}
          fetch-depth: 0
          cache: yarn
      - uses: nrwl/nx-set-shas@v2
      if: ${{github.event.pull_request == true }}
      - name: Installing Yarn
      - run: npm install yarn

      if: ${{github.event.pull_request == true }}
      - name: Installing Dependencies
      - run: yarn install
      if: ${{github.event.pull_request == true }}
      - name: Running nx affected lint
      - run: yarn nx affected --target=lint --parallel=3
      if: ${{github.event.pull_request == true }}
      - name: Running nx affected test
      - run: yarn nx affected --target=test --parallel=3 --ci --code-coverage
      if: ${{github.event.pull_request == true }}
      - name: Running nx affected build
      - run: yarn nx affected --target=build --parallel=3
      if: ${{github.event.pull_request == true }}
      - name: Running nx affected e2e
      - run: yarn nx affected --target=e2e 

      - run: yarn nx workspace-lint
      - run: yarn nx format:check