name: Deafult Test
on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: Generate cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'develop'
      
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

        
      - name: Install yarn
        run: npm install yarn -g

      - name: Cache Yarn Packages
      id: cache-yarn-packages
      uses: actions/cache@v2
      with:
        path: ~/.cache
        key: yarn-packages-${{ hashFiles('**/yarn.lock') }}
      
      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Lint test affected
        run: yarn nx affected:lint --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

      - name: Build test affected
      run: yarn nx affected:build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

      - name: Unit test affected
        run: yarn nx affected:test --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

      - name: E2E test affected
        run: yarn nx affected:e2e --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

      - name: Test all
      run: |
        yarn nx run-many --target=lint --all --skip-nx-cache --parallel
        yarn nx run-many --target=build --all --skip-nx-cache --parallel
        yarn nx run-many --target=test --all --skip-nx-cache --parallel --coverage
        yarn nx run-many --target=e2e --all --skip-nx-cache --parallel --coverage 

      name: Merge coverage reports
      run: node ./tools/scripts/merge-reports.js